version: "3.3"
services:
    bookshelf-socket-server:
        build: .
        image: bookshelf-client-socket:1.0
        container_name: bookshelf-client-socket
        ports:
            - 8080:8080
            - 8082:8081
