server:
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bookshelf
    username: sharp
    password: 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        generate_statistics: true
    hibernate:
      ddl-auto: update
    show-sql: true