version: "3.3"
services:
    bookshelf-socket-server:
        build: ../console
        image: bookshelf-console-app:1.0
        container_name: bookshelf-console-app
        ports:
            - 8080:8080
            - 8082:8081
        links:
            - mysql
    mysql:
        image: mysql:8.0.30
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=sharp
            - MYSQL_PASSWORD=1
            - MYSQL_DATABASE=bookshelf
        container_name: mysql-bookshelf-console-app
        ports: 
            - 3307:3306
        volumes:
            - ./db:/var/lib/my-sql
